# dvc.yaml
# Definición del Pipeline de MLOps
stages:
  # ETAPA 1: Preparación de Datos
  prepare:
    cmd: python src/data_prep.py
    deps:
    - src/data_prep.py
    - data/raw/telco_churn.csv
    outs:
    - data/processed/telco_churn_ok.csv
  # ETAPA 2: Entrenamiento del Modelo
  # Esta etapa dependerá de las salidas de la etapa 'prepare'
