# params.yaml

# ----------------------------------------------------
# 1. Parámetros de la Etapa 'train' (Hiperparámetros)
# ----------------------------------------------------
train:
  # Parámetros para el modelo de Regresión Logística
  lr_params:
    C: 0.1           # Hiperparámetro de regularización
    max_iter: 200 # 100    # Número de iteraciones
    solver: 'lbfgs'  # (Añadido: Asumiendo un solver común)
    class_weight: 'balanced'  # <--- ¡NUEVO PARÁMETRO CLAVE!
  
  # Parámetros para el modelo de Random Forest (basado en tus scripts anteriores)
  # rf_params:
    # n_estimators: 100
    # max_depth: 5
    # random_state: 42
  # para la etapa 6, se decide utilizar el modelo de regresion por mejores resultados, se deja vacio los hiper de random forest:
  rf_params: {}

# ----------------------------------------------------
# 2. Parámetros Generales (Split y Rutas)
# ----------------------------------------------------
general:
  split:
    test_size: 0.2
    random_state: 42
  paths:
    # Estas rutas suelen ser dependencias para DVC
    raw_data: ../data/raw/telco_churn.csv
    model_path: ../models/telco_churn_model.pkl
    metrics_path: ../model/metrics.json